name: Build and Publish Keycloak Theme

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Maven Action
        uses: s4u/setup-maven-action@v1.18.0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          always-auth: true
          registry-url: https://npm.pkg.github.com/
          scope: '@accurasgmbh'

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Build Keycloak Theme
        run: pnpm run build-keycloak-theme

      - name: Upload JAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: accuras-keycloak-theme
          path: dist_keycloak/keycloak-theme-for-kc-22-to-25.jar
          retention-days: 7